### ISSUE TITLE
Redesign home page in creative way.

### ISSUE THREAD

**Issue by kiranshahi** [kiranshahi/blog#52]
Hi, I want to redesign my blog home page so that it looks more attractive and  creative. Live version of blog : http://www.kirans.me/blog

**Comment by mcastre** [comment]
hello @kiranshahi I'd love to help you out on this! 

Are there any design styles you would like to see on this view? Would you prefer to get static mockups of the blog before development?

**Comment by kiranshahi** [comment]
Hi @mcastre currently I don't have any mockups for it. Any kind of contributions are welcome. Just need to make more attractive looks for blog

**Comment by BestDanelleEver** [comment]
Can i try this?

**Comment by kiranshahi** [comment]
@BestDanelleEver yes, you can

**Comment by dilumdesilva** [comment]
Hello @kiranshahi I would like to contribute on this ......

**Comment by kiranshahi** [comment]
@dilum1995 you are welcome
